#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

/* CONFIGURATION */
#define ALLOCATION_SIZE 1024
#define BLOCK_SIZE 128
#define EXTENSION 256

#define PRINT_DEBUG_TRACE 0u
#define DEBUG_OFFLINE 1u

#endif // CONFIG_H_INCLUDED
